keys:
  - &admin_jan 35135CE577AD711F38259A99366572BE7D6C78A2
  - &server_vpsDev age1jslv70zx6nudxdsznejmpetj3ffzdj0sdh65793nps4raqa6zcxsek5dnq
creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
    - pgp:
      - *admin_jan
      age:
      - *server_vpsDev
  - path_regex: tunnel/[^/]+\.conf$
    key_groups:
    - pgp:
      - *admin_jan
      age:
      - *server_vpsDev
