keys:
  - &admin_jan 35135CE577AD711F38259A99366572BE7D6C78A2
  - &server_vpsDev age1a7gvxdw2ttnxz07z02qa3h0ceqse5j9ev3xec0k86tjv44un59yqsfv6q5
creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
    - pgp:
      - *admin_jan
      age:
      - *server_vpsDev
